# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Marton Bodonyi
tagline:          'Software developer'
description:      'Front-end, ReactNative, React, NodeJS and ex-Drupal developer.'
baseurl:          /

author:
  name:           'Marton Bodonyi'
  url:            https://github.com/martsie

paginate:         5

sass:
    sass_dir: _sass

sass:
    style: compressed

# Custom vars
version:          1.0

github:
  repo:           https://github.com/martsie/
